#!/usr/bin/env bash
# coment for the checker

# coimment for the func
func ()
{
        dig "$2.$1" | grep -A1 'ANSWER SECTION:' | grep "$2" | awk -v var="$2" '{print "The subdomain " var " is a " $4 " record and points to " $5}'
}

# comment for che
if [ -z $2 ]
then
        func "$1" "www"
        func "$1" "lb-01"
        func "$1" "web-01"
        func "$1" "web-02"
else
        func "$1" "$2"
fi

