#!/usr/bin/env bash
# comment for the checker

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
