#!/usr/bin/env bash
# comment for the checker

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo sed -i '/server_name _;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
