#!/usr/bin/env bash
#comment for the checker

sudo apt-get update
sudo apt -y install nginx
sudo echo "Ceci n'est pas une page" > /var/www/html/404-page.html
sudo chmod 777 /var/www/html/404-page.html
sudo sed -i '55i error_page 404 /404-page.html;' /etc/nginx/sites-enabled/default
sudo service nginx restart
