#!/usr/bin/env bash
# comment for the checker

sudo apt update
sudo apt-get -y install nginx
sudo sed -i "/listen 80 default_server/a add_header X-Served-By '$HOSTNAME';" /etc/nginx/sites-enabled/default
sudo service nginx restart
