#!/usr/bin/env bash
# comment for the checker
pkill apache2
chmod 700 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
