#!/usr/bin/env bash
# comment for the checker
chmod 744 /etc/nginx/nginx.conf
sed -i "1iuser nginx;" /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
su -c "service nginx restart" nginx
